// Generates programs_seed.sql from ../../programs/*.json.
// Run after editing templates; apply the output with supabase db push / psql.
// Runs the contract validator first — invalid templates never reach SQL.

import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const programsDir = join(here, '..', '..', 'programs');

execFileSync(process.execPath, [join(programsDir, 'validate.mjs')], { stdio: 'inherit' });

const esc = (s) => s.replaceAll("'", "''");
const rows = [];

for (const file of readdirSync(programsDir).filter((f) => f.endsWith('.json')).sort()) {
  const p = JSON.parse(readFileSync(join(programsDir, file), 'utf8'));
  rows.push(
    `('${esc(p.program_id)}', '${esc(p.name)}', '${esc(JSON.stringify(p))}'::jsonb, ` +
    `${p.is_free}, '${esc(p.schema_version)}')`,
  );
}

const sql = `-- Generated by backend/seed/generate_seed_sql.mjs — do not edit by hand.
insert into programs (program_id, name, definition, is_free, schema_version)
values
${rows.join(',\n')}
on conflict (program_id) do update set
  name = excluded.name,
  definition = excluded.definition,
  is_free = excluded.is_free,
  schema_version = excluded.schema_version;
`;

const out = join(here, 'programs_seed.sql');
writeFileSync(out, sql);
console.log(`wrote ${out} (${rows.length} programs)`);
